### ISSUE TITLE
Feature request: Set Custom Cookie Parameters or Additional cookie

### ISSUE THREAD

**Issue by ChrisOgden** [kinde-oss/kinde-sveltekit-sdk#32]
### Prerequisites

- [X] I have searched the repository’s issues, [Kinde community](https://thekindecommunity.slack.com/archives/C04K34HUV9B) and [public roadmap](https://updates.kinde.com/board) to ensure my feature request isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### What is the problem you’re trying to solve?

I would like to use the sveltekit SDK to set a cookie for *.example.com not just app.example.com so that the cookie can be used for related sub services on different subdomains.

### What solution would you like to see?

The ability to set additional or modify parameters used to create the cookie during the login flow. Optionally create a secondary cookie for support on the other subdomains.

### Additional information

I have tried the following and it works except at logout the cookie can't be properly deleted as part of logout. Due to that the app throws a 500 error due to the cookie that it can't decode

```
const isAuthentication = await kindeAuthClient.isAuthenticated(
request as unknown as SessionManager
);
let userProfile = null
if (isAuthentication) {
  // Intercept cookies set by Kinde
  const kindeCookie = cookies.get('kinde_access_token')
  
  if (kindeCookie) {
	  cookies.set('kinde_access_token', kindeCookie, {
		  domain: '.example.com', // Set the domain for all subdomains
		  path: '/',
		  secure: true, // Make sure the cookie is sent over HTTPS
		  sameSite: 'None' // Enable cross-origin cookie sharing
	  })
  }
} else {
cookies.delete('kinde_access_token', {
			domain: '.example.com',
			path: '/',
			secure: true,
			sameSite: 'None'
		})
}
```

**Comment by DanielRivers** [comment]
Hi @ChrisOgden 

I have released a pre-release with this resolved: `@kinde-oss/kinde-auth-sveltekit@next`

Could you please validate the fix?  

You can define the cookie domain with the environment variable `KINDE_COOKIE_DOMAIN`

**Comment by ChrisOgden** [comment]
@DanielRivers This works as expected and intended. 

It does not solve my implementation issue but I think based on our discussion that is a result of my error, not the SDK. I should be using the token from sveltekit sdk to request a token from the backend express API for use specifically with the backend express API. I will follow up separately on that one after reviewing the documentation again.
